export const SEED_QUESTIONS = [
  {
    order_index: 1,
    prompt: "PM 在上线前一天改了需求范围，你通常会…",
    option_a: "直接做，别废话",
    option_b: "先问清楚原因，再决定",
    option_c: "直接 push back",
    option_d: "表面答应，内心翻白眼",
  },
  {
    order_index: 2,
    prompt: "同事没赶上 deadline，你的第一反应是…",
    option_a: "帮忙补位，大家都不容易",
    option_b: "问一下原因，看看能不能一起解决",
    option_c: "向上汇报，这不是我的锅",
    option_d: "下次提前预警，避免再发生",
  },
  {
    order_index: 3,
    prompt: "团队要约一个全员会议，你更倾向…",
    option_a: "越短越好，15分钟搞定",
    option_b: "有明确 agenda 就行",
    option_c: "不需要开会，Slack 说清楚就好",
    option_d: "开久一点没关系，把事情讨论透",
  },
  {
    order_index: 4,
    prompt: "Code review 时有人对你的方案提出不同意见，你会…",
    option_a: "认真听，有道理就改",
    option_b: "解释我的思路，争取说服对方",
    option_c: "直接按他说的改，省事",
    option_d: "拉个小会讨论，避免文字误解",
  },
  {
    order_index: 5,
    prompt: "你理想的 Slack/消息沟通方式是…",
    option_a: "能一条消息说清楚就别分三条发",
    option_b: "随时发，想到什么说什么",
    option_c: "非紧急的事情统一时间回复",
    option_d: "重要的事情还是打电话或面聊",
  },
  {
    order_index: 6,
    prompt: "关于周末和加班，你的态度是…",
    option_a: "活干完就好，不在意时间",
    option_b: "偶尔可以，但别成为常态",
    option_c: "工作时间内解决，周末是我的",
    option_d: "看项目阶段，关键节点可以拼一下",
  },
  {
    order_index: 7,
    prompt: "做重要决策时，你更偏向…",
    option_a: "快速拍板，边做边调",
    option_b: "收集足够信息后再做决定",
    option_c: "跟团队讨论达成共识",
    option_d: "让最有经验的人来决定",
  },
  {
    order_index: 8,
    prompt: "收到批评性反馈后，你通常会…",
    option_a: "先消化情绪，再理性分析",
    option_b: "当场讨论，搞清楚具体问题",
    option_c: "默默记住，用行动证明自己",
    option_d: "反思是否合理，不合理会反驳",
  },
  {
    order_index: 9,
    prompt: "团队内部有人起冲突，你会…",
    option_a: "主动调解，团队和谐最重要",
    option_b: "不掺和，让他们自己解决",
    option_c: "找 leader 介入处理",
    option_d: "私下分别聊聊，了解情况",
  },
  {
    order_index: 10,
    prompt: "接手一个全新项目，你第一步通常是…",
    option_a: "先看现有代码和文档",
    option_b: "找相关的人聊聊背景",
    option_c: "直接开干，边做边了解",
    option_d: "先列计划，搞清楚目标和边界",
  },
];
