export const SEED_QUESTIONS = [
  {
    order_index: 1,
    prompt: "上线前一天，PM 说「需求有变」。你…",
    option_a: "行吧，改就改，少废话",
    option_b: "先搞清楚为什么变，再决定干不干",
    option_c: "不改。这个时间点改需求不合理",
    option_d: "嘴上说好的，心里已经在更新简历",
  },
  {
    order_index: 2,
    prompt: "你负责的模块上线后出了 bug，同事在群里 @你。你…",
    option_a: "秒回：在看了，马上修",
    option_b: "先复现确认，再回复",
    option_c: "反手甩一个 git blame：这段不是我写的",
    option_d: "已读不回，默默打开 IDE 修完再说",
  },
  {
    order_index: 3,
    prompt: "周一早上，日历上出现一个没有 agenda 的一小时会议。你…",
    option_a: "直接 decline，没 agenda 不开会",
    option_b: "先问一下会议目的，再决定参不参加",
    option_c: "参加但带着电脑做自己的事",
    option_d: "去了，但全程希望会议快点结束",
  },
  {
    order_index: 4,
    prompt: "Code review 里有人留了 20 条 comment，大部分是风格偏好。你…",
    option_a: "一条条讨论，review 就是用来对齐的",
    option_b: "重要的改，鸡毛蒜皮的 resolve 掉",
    option_c: "全改了，吵这个浪费时间",
    option_d: "约个 5 分钟的 call 说清楚，文字扯不完",
  },
  {
    order_index: 5,
    prompt: "一个同事习惯在 Slack 上一句话拆成七八条发。你…",
    option_a: "无所谓，这是人家的习惯",
    option_b: "内心 OS：能不能一次说完",
    option_c: "静音了这个对话",
    option_d: "直接告诉他：兄弟，消息合并一下",
  },
  {
    order_index: 6,
    prompt: "周五下午 6 点，leader 说「这个今晚能搞定吗」。你…",
    option_a: "能，我弄完再走",
    option_b: "看看是不是真的紧急，紧急就加班",
    option_c: "周一行不行？今晚有安排了",
    option_d: "嘴上说行，但开始计算调休怎么补回来",
  },
  {
    order_index: 7,
    prompt: "团队在两个技术方案之间纠结了三天。你…",
    option_a: "先选一个干，错了再改，别空转了",
    option_b: "做个对比文档，用数据说话",
    option_c: "让大家投票，民主决策",
    option_d: "找最资深的人拍板，别浪费时间了",
  },
  {
    order_index: 8,
    prompt: "1:1 里你的 manager 说「最近你的产出需要提升」。你…",
    option_a: "先消化一下，别当场炸",
    option_b: "当场追问具体哪里不行，要例子",
    option_c: "好的好的，然后回去该干嘛干嘛",
    option_d: "反问一句：你觉得合理的产出标准是什么？",
  },
  {
    order_index: 9,
    prompt: "两个同事闹矛盾，开始在群里阴阳怪气。你…",
    option_a: "私聊调解，别让团队气氛变差",
    option_b: "不关我事，眼不见心不烦",
    option_c: "截图发给 leader，该管管了",
    option_d: "分别私下聊，搞清楚到底怎么回事",
  },
  {
    order_index: 10,
    prompt: "入职新公司第一天，你打开代码仓库。你…",
    option_a: "先看 README 和文档",
    option_b: "找个人带一下，口传效率高",
    option_c: "直接 clone 下来跑起来，边跑边看",
    option_d: "先花一天搞清楚项目架构和技术栈",
  },
];

export const SEED_QUESTIONS_EN = [
  {
    order_index: 1,
    prompt: "One day before launch, the PM says \"scope changed.\" You…",
    option_a: "Fine. Just tell me what to change",
    option_b: "Why? Let me understand the reason first",
    option_c: "No. Changing scope now is not reasonable",
    option_d: "\"Sure\" (starts updating resume in another tab)",
  },
  {
    order_index: 2,
    prompt: "Your module has a prod bug. A colleague @mentions you in the group chat. You…",
    option_a: "Instant reply: Looking into it, fixing now",
    option_b: "Reproduce first, then respond",
    option_c: "git blame — this wasn't my code",
    option_d: "Read but don't reply. Fix silently. Announce later",
  },
  {
    order_index: 3,
    prompt: "Monday morning. A 1-hour meeting with no agenda appears on your calendar. You…",
    option_a: "Decline. No agenda, no meeting",
    option_b: "Ask what it's about first",
    option_c: "Join but work on your own stuff the whole time",
    option_d: "Attend, but internally pray it ends early",
  },
  {
    order_index: 4,
    prompt: "A reviewer leaves 20 comments on your PR. Most are style preferences. You…",
    option_a: "Discuss each one — reviews are for alignment",
    option_b: "Fix the real issues, resolve the nitpicks",
    option_c: "Change everything. Not worth the argument",
    option_d: "Hop on a quick call — text threads are endless",
  },
  {
    order_index: 5,
    prompt: "A colleague sends every Slack message as a separate line. Seven messages for one thought. You…",
    option_a: "Whatever, that's just how they communicate",
    option_b: "Internal screaming: PLEASE SEND ONE MESSAGE",
    option_c: "Mute the conversation",
    option_d: "Tell them directly: hey, maybe batch your messages?",
  },
  {
    order_index: 6,
    prompt: "Friday 6 PM. Your lead asks: \"Can you finish this tonight?\" You…",
    option_a: "Sure, I'll wrap it up before leaving",
    option_b: "Is it actually urgent? If yes, I'll stay",
    option_c: "Can it wait until Monday? I have plans",
    option_d: "\"Yeah sure\" (starts calculating comp time)",
  },
  {
    order_index: 7,
    prompt: "The team has been stuck between two technical approaches for three days. You…",
    option_a: "Just pick one and iterate. Stop spinning",
    option_b: "Write a comparison doc with data",
    option_c: "Let the team vote. Democracy",
    option_d: "Ask the most senior person to decide. Move on",
  },
  {
    order_index: 8,
    prompt: "In your 1:1, your manager says \"your output needs to improve.\" You…",
    option_a: "Take a breath. Don't react right now",
    option_b: "Ask for specific examples on the spot",
    option_c: "Nod along, then go back to doing your thing",
    option_d: "Counter: \"What does 'reasonable output' look like to you?\"",
  },
  {
    order_index: 9,
    prompt: "Two colleagues are beefing. They're now passive-aggressive in the group chat. You…",
    option_a: "DM both privately. Don't let the team vibe rot",
    option_b: "Not my circus, not my monkeys",
    option_c: "Screenshot and send to the manager",
    option_d: "Talk to each one separately. Understand first",
  },
  {
    order_index: 10,
    prompt: "First day at a new company. You open the codebase. You…",
    option_a: "Read the README and docs first",
    option_b: "Find someone to walk you through it",
    option_c: "Clone, run, poke around — learn by doing",
    option_d: "Spend day one mapping the architecture",
  },
];
